# 2.2 数据操作

In [1]:
import torch

PyTorch中， ```torch.Tensor``` 是存储和变换数据的工具。```Tensor```提供GPU计算和自动求梯度等多种功能，这些使```Tensor```更加适合深度学习

## 2.2.1 创建```Tensor```

创建一个5*3未初始化的```Tensor```

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39],
        [9.4592e-39, 1.0561e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 1.0745e-38],
        [9.6429e-39, 1.0561e-38, 9.1837e-39]])


创建一个5*3随机初始化的```Tensor```

In [5]:
x = torch.rand(5,3)
x

tensor([[0.6987, 0.2373, 0.6686],
        [0.3002, 0.8360, 0.5440],
        [0.0285, 0.4761, 0.3905],
        [0.6661, 0.4206, 0.5232],
        [0.6871, 0.1418, 0.9059]])

创建一个5*3long型全0的```Tensor```

In [3]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


还可以直接根据数据创建

In [9]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])